DEFINE_TYPEINFO_POD(short);
DEFINE_TYPEINFO_POD(short *);
DEFINE_TYPEINFO_POD(int);
DEFINE_TYPEINFO_POD(int *);
DEFINE_TYPEINFO_POD(long);
DEFINE_TYPEINFO_POD(long *);
DEFINE_TYPEINFO_POD(char);
DEFINE_TYPEINFO_POD(char *);
DEFINE_TYPEINFO_POD(float);
DEFINE_TYPEINFO_POD(std::string);

